### ISSUE TITLE
start.sh script doesn't test return values

### ISSUE THREAD

**Issue by lfrancois** [trackit/trackit2-home#59]
Hi @zanchi-r !

Your startup.sh doesn't test if it goes well or not before to say it. Can you fix it please?
```
./trackit2/scripts/awsenv default docker-compose up -d
echo "===> installation completed, TrackIt is now running on port 80"
```

Also trying to understand why you need aws-cli. Can you clarify please?

**Comment by zanchi-r** [comment]
Hi,

docker-compose always returns 0, so I had to come up with a workaround.
This is implemented in commit 7648983927bc099e11aa344bc57d483d7702f260

Closing this issue.
