### ISSUE TITLE
Service 'sql' failed to build

### ISSUE THREAD

**Issue by jt89** [trackit/trackit2-home#65]
hi,

did everything as described in docs (executed start.sh); the following error occured.

`ERROR: Service 'sql' failed to build: COPY failed: stat /opt/docker/tmp/docker-builder100241954/db/schema.sql: no such file or directory`

System:
`Docker version 18.04.0-ce, build 3d479c0`
`docker-compose version 1.21.0, build 5920eb0`
on a cent os 7 (latest).
I also tried it with stable ce version - same outcome.

Thank you in advance.

**Comment by giubil** [comment]
Hello jt89,

It seems that docker cannot find the `schema.sql` that should be located in `./trackit2/docker/sql/schema.sql`.

Could you run `ls -la ./trackit2/docker/sql` from the root of the repo and paste the output here ?

Thanks

**Comment by lfrancois** [comment]
Thank you @jt89, can you try to follow this step by step guide? 
- https://trackit.io/installing-setting-trackit-up-step-by-step/

We are investigating the building issue. Thank you for your help.

**Comment by jt89** [comment]
hi giubil,
i checked the file's presence:
`drwxr-xr-x. 2 root root  42 19. Apr 17:30 .`
`drwxr-xr-x. 3 root root  57 19. Apr 17:30 ..`
`-rw-r--r--. 1 root root 122 19. Apr 17:30 Dockerfile`
`lrwxrwxrwx. 1 root root  19 19. Apr 17:30 schema.sql -> ../../db/schema.sql`
the symlink works too.

francois, yes I followed this repo's readme and the more detailed guide you mentioned as well.

**Comment by giubil** [comment]
Hey,

We found the problem on our side, and it is fixed and merged now.

Thank you for your help, and if you experience an other problem, do not hesitate to open an issue.

Closing the issue now.
